site_name: Voyages and Fleet Simulation Solution Microservices
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-ms
nav:
  - Welcome: index.md
  - Fleet Simulator: fleetms.md
  - Voyage management microservice: voyagesms.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences