# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: us.icr.io/ibmcaseeda/kc-voyagesms
  tag: latest
  pullPolicy: Always
  pullSecret: browncompute-registry-secret
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 3000
  periodSeconds: 1000
service:
  name: node
  type: NodePort
  servicePort: 3000
  nodePort: 31000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: false
kafka:
  brokersConfigMap: kafka-brokers
eventstreams:
  #env: IBMCLOUD #DEPRECATED - TO BE REMOVED COMPLETELY
  enabled: true
  apikeyConfigMap: eventstreams-apikey
  caPemFileRequired: true
  caPemFilePath: "/etc/ssl/certs/kcontainer"
  caPemFileName: "es-cert.pem"
  caPemSecretName: es-ca-pemfile
serviceAccountName: default
