# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: us.icr.io/ibmcaseeda/kc-fleetms
  tag: latest
  pullPolicy: Always
  pullSecret: browncompute-registry-secret
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
base:
  replicaCount: 1
  enabled: false
service:
  name: Node
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  nodePort: 31300
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: false
eventstreams:
  brokersConfigMap: kafka-brokers
  apikeyConfigMap: eventstreams-apikey
  #brokers:
  #  - kafka03-prod02.messagehub.services.us-south.bluemix.net:9093
  #  - kafka01-prod02.messagehub.services.us-south.bluemix.net:9093
  env: IBMCLOUD
serviceAccountName: default
